messages:
  start: "Привет! Давай начнем! Как тебя зовут?"
  ask_name: "Здравствуй!\nКак тебя зовут?"
  ask_dob: "Здравствуйте, %s. Введите свою дату рождения в формате YYYY-MM-DD."
  invalid_dob_format: "%s, отправьте дату рождения в формате YYYY-MM-DD!"
  invalid_dob: "%s, вы не могли родиться в эту дату."
  weeks_lived: "%s, вы прожили %d недель!"
  dob_already_set: "Вы уже ввели свою дату рождения!\nЕсли вы хотите ее изменить, напишите /change."
  change_dob: "%s, введите новую дату рождения в формате YYYY-MM-DD."
  unknown_command: "Неизвестная команда <3"
  start_with: "Сначала начните с команды /start"

database:
  path: "users.db"